#+title: My Ferris Sweep QMK layout
#+author: bsag
#+email: butshesagirl@rousette.org.uk

This is my custom layout for my 3x5+2 [[https://www.rousette.org.uk/archives/ferris-sweep-keyboard-and-layout/][Ferris Sweep keyboard]]. I am using [[https://ieants.cc/beakl/][BEAKL]] as my full time layout at the moment. I started with the 15 version, but have switched to the 27 version to avoid some of the single finger bigram (SFB) issues, and I have also swapped Y and H for the same reason. I'm still building my speed back up again, but it does feel even more comfortable. On the Ferris, pressing the homerow pinkie keys is actually quite comfortable, so I'm fine having a common key like H on that key.

Otherwise, I use one-shot modifiers, and layers accessed via holding thumb keys.
On the layers, I mostly try to keep the keys on the opposite hand to the one
holding the modifiers (like Miroyoku), but there are a few exceptions where it makes sense to
have a key on a particular layer and there's no room for it on the chosen side.

I also use combos for enter, tab, escape, backspace and delete, as well as all
the brackets, which are mostly on the home row.

I have modified [[https://github.com/mattgemmell/qmk_firmware][Matt
Gemmell's]] ~update-keymap-diagram.py~ script so that it would work with my layout,
and that generates the image below.

[[./keymap_diagram.svg]]
