MOUSEKEY_ENABLE     = no     # Mouse keys
RGB_MATRIX_ENABLE   = no
LTO_ENABLE          = yes
COMBO_ENABLE 		= yes
AUTO_SHIFT_ENABLE = yes
SRC += caps_word.c
SRC += oneshot.c
SRC += swapper.c
SRC += layermodes.c
